Testigbranch
Hossain2024/BloomMoods pull request #16
Opened 2024-05-14 21:58 UTC by Hossain2024

2024-05-14 22:16 UTC, amanda65 requested changes
There is already a hideBottomNavigation() method in the MainActivity. Please use that instead to avoid redundant code. Also, NavController is already initialized onCreate in MainActivity, so there is no need to initialize it twice.

2024-05-14 23:38 UTC, amanda65 approved these changes

2024-05-15 00:46 UTC, cchelsd approved these changes

2024-05-15 15:16 UTC, rainiechi approved these changes

2024-05-15 15:16 UTC, merged